name: Strava Export

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write
  
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

concurrency:
  group: strava-export
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
      STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
      STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install --upgrade pip
          pip install --no-cache-dir requests icalendar pandas reverse_geocoder

      - run: |
          echo "Running Strava export..."
          python export_strava_activities.py
          python strengthlog-to-json.py
          python json-to-html.py
          python json-to-ics.py

      # commit updated files back to repo

      - name: Commit updated data
        if: always()
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated export $(date +'%Y-%m-%d %H:%M')" || echo "No changes"
          git push
          echo "Done!"
